---
language: python
python: "2.7"
env:
  - SITE=site.ci.yml
before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -qq python-apt python-pycurl
install:
  - pip install ansible==1.6.0
  - ansible --version
  - pip install https://github.com/willthames/ansible-lint/archive/master.zip
script:

  - cd tests

  - echo localhost > inventory

  # Check the role/playbook's syntax.
  - "ansible-playbook -i inventory $SITE --syntax-check"

  # Check the role/playbook's lint.
  - "ansible-lint $SITE"

  # Run the role/playbook with ansible-playbook.
  - "ansible-playbook -i inventory $SITE --connection=local --sudo -vv"

  # Run the role/playbook again.
  - "ansible-playbook -i inventory $SITE --connection=local --sudo -vv | tee idempotent.log"

  # Checking to make sure it's idempotent.
  - >
    grep -q 'changed=0.*failed=0' idempotent.log
    && (echo 'Idempotence test: pass' && exit 0)
    || (echo 'Idempotence test: fail' && exit 1)
