---
language: python
python: "2.7"
env:
  - SITE=test.yml
before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -qq python-apt python-pycurl
install:
  - pip install ansible
  - pip install https://github.com/willthames/ansible-lint/archive/master.zip
script:

  - echo localhost > tests/inventory

  # Check the role/playbook's syntax.
  - "cd tests && ansible-playbook -i inventory $SITE --syntax-check"

  # Check the role/playbook's lint.
  - "ansible-lint tests/$SITE"

  # Run the role/playbook with ansible-playbook.
  - "cd tests && ansible-playbook -i inventory $SITE --connection=local --sudo -vv"

  # Run the role/playbook again, checking to make sure it's idempotent.
  - >
    cd tests && ansible-playbook -i inventory $SITE --connection=local --sudo -vv
    | grep -q 'changed=0.*failed=0'
    && (echo 'Idempotence test: pass' && exit 0)
    || (echo 'Idempotence test: fail' && exit 1)
