---
- name: Include OS-specific variables.
  include_vars: "{{ ansible_distribution }}.yml"

- name: Fetch installer
  get_url:
    url="http://www.getchef.com/chef/download?p={{ chef_client_package['platform'] }}&pv={{ chef_client_package['platform_version'] }}&m={{ chef_client_package['arch'] }}&v={{ chef_client_version }}&prerelease=false"
    dest="{{ chef_client_package['installer_dest'] }}"
  register: register_installer_url
  tags: [chef-client, download]

- include: package_Debian.yml
  when: ansible_os_family == 'Debian'

- include: package_RedHat.yml
  when: ansible_os_family == 'RedHat'
