---
- name: install_sh | Fetch sh
  get_url:
    url=https://www.opscode.com/chef/install.sh
    dest={{ chef_client_installer_dir }}/install.sh
  register: register_sh_url
  tags: [chef-client, download]

- name: install_sh | Execute installer
  command: bash {{ chef_client_installer_dir }}/install.sh
  register: register_sh_install
  tags: [chef-client, install]
