---
- name: Ubuntu | Set metadata facts
  set_fact:
    platform: "ubuntu"
    platform_version: {{ ansible_distribution_version }}
    arch: {{ ansible_architecture }}
    installer_dest: "{{ installer_dir }}/{{ version }}.deb"
  tags: [chef-client, fact]

- name: Ubuntu | Fetch installer
  get_url:
    url="http://www.getchef.com/chef/download?p={{ platform }}&pv={{ platform_version }}&m={{ arch }}&v={{ version }}&prerelease=false"
    dest="{{ installer_dest }}"
  register: register_installer_url
  tags: [chef-client, download]

- name: Ubuntu | Install deb package
  apt: deb="{{ installer_dest }}"
  register: register_deb
  tags: [chef-client, installer, deb]
  when: installer_dest is defined and register_installer_url.changed
