---
- name: RedHat | Install yum package
  yum: name="{{ chef_client_package['installer_dest'] }}"
  register: register_yum
  tags: [chef-client, installer, yum]
  when: chef_client_package['installer_dest'] is defined
