---
- name: Debian | Install deb package
  apt: deb="{{ chef_client_package['installer_dest'] }}"
  register: register_deb
  tags: [chef-client, installer, deb]
  when: chef_client_package['installer_dest'] is defined
