---
- name: MacOSX | Set metadata facts
  set_fact:
    platform: "mac_os_x"
    platform_version: {{ ansible_distribution_version }}
    arch: "x86_64"
    installer_dest: "{{ installer_dir }}/{{ version }}.dmg"
  tags: [chef-client, fact]

- name: MacOSX | Fetch installer
  get_url:
    url="http://www.getchef.com/chef/download?p={{ platform }}&pv={{ platform_version }}&m={{ arch }}&v={{ version }}&prerelease=false"
    dest="{{ installer_dest }}"
  register: register_installer_url
  tags: [chef-client, download]
