---
- name: Centos | Set metadata facts
  set_fact:
    platform: "el"
    platform_version: "5"
    arch: "x86_64"
    installer_dest: "{{ installer_dir }}/{{ version }}.dpkg"
  tags: [chef-client, fact]

- name: Centos | Fetch installer
  get_url:
    url="http://www.getchef.com/chef/download?p={{ platform }}&pv={{ platform_version }}&m={{ arch }}&v={{ version }}&prerelease=false"
    dest="{{ installer_dest }}"
  register: register_installer_url
  tags: [chef-client, download]

- name: Centos | Install package
  yum: name="{{ installer_dest }}" state=present
  tags: [chef-client, installer, yum]
  when: installer_dest is defined and register_installer_url.changed
